# Generated by Django 3.0.5 on 2020-04-02 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('Comment', models.TextField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
